import type { Module } from '../types'
import chapitre1 from './lessons/chapitre1.md?raw'
import chapitre2 from './lessons/chapitre2.md?raw'
import chapitre3 from './lessons/chapitre3.md?raw'
import chapitre4 from './lessons/chapitre4.md?raw'

export const curriculum: Module[] = [
  {
    id: 'm1',
    title: 'Module 1 — Fondamentaux de Lua',
    summary: 'Syntaxe, variables, types, opérateurs et structures de contrôle.',
    chapters: [
      {
        id: 'm1c1',
        title: 'Chapitre 1 — Introduction et premiers pas',
        summary: 'Syntaxe de base, variables, types de données et opérateurs.',
        items: [
          { kind: 'lesson', id: 'm1c1-cours', title: 'Cours', content: chapitre1 },

          {
            kind: 'exercise',
            id: 'm1c1-ex1',
            title: 'Exercice 1 — Variables et types',
            difficulty: 'facile',
            statement: [
              'Déclarez les variables suivantes en respectant les conventions de nommage, puis affichez le **type** de chacune avec `type()` :',
              '',
              '1. une variable locale `firstName` contenant votre prénom (en anglais)',
              '2. une variable locale `playerAge` contenant un âge',
              '3. une variable booléenne `likesToProgram`',
              '4. une constante `MAX_PLAYERS` valant `32`',
              '',
              'La sortie doit contenir au moins les mots `string`, `number` et `boolean`.',
            ].join('\n'),
            starter: [
              '-- Déclarez vos variables ici',
              'local firstName = ',
              '',
              '-- Affichez le type de chaque variable, par exemple :',
              '-- print("firstName:", type(firstName))',
            ].join('\n'),
            solution: [
              'local firstName = "Alice"',
              'local playerAge = 28',
              'local likesToProgram = true',
              'local MAX_PLAYERS = 32',
              '',
              'print("firstName:", type(firstName))',
              'print("playerAge:", type(playerAge))',
              'print("likesToProgram:", type(likesToProgram))',
              'print("MAX_PLAYERS:", type(MAX_PLAYERS))',
            ].join('\n'),
            tests: [
              { name: 'Un type "string" est affiché', code: 'assert(printed("string"), "Aucune string affichée")' },
              { name: 'Un type "number" est affiché', code: 'assert(printed("number"), "Aucun number affiché")' },
              { name: 'Un type "boolean" est affiché', code: 'assert(printed("boolean"), "Aucun boolean affiché")' },
            ],
            hints: [
              'Pour afficher un type : print(type(maVariable)).',
              'Un booléen vaut true ou false, sans guillemets.',
            ],
          },

          {
            kind: 'exercise',
            id: 'm1c1-ex2',
            title: 'Exercice 2 — Calculs arithmétiques',
            difficulty: 'facile',
            statement: [
              'Les deux nombres sont déjà définis (`firstNumber = 15`, `secondNumber = 4`).',
              '',
              'Affichez, dans cet ordre, leur **somme**, leur **différence**, leur **produit**, leur **division** et le **reste** (modulo).',
            ].join('\n'),
            starter: [
              'local firstNumber = 15',
              'local secondNumber = 4',
              '',
              '-- Affichez somme, différence, produit, division et reste',
              'print("Sum:", )',
            ].join('\n'),
            solution: [
              'local firstNumber = 15',
              'local secondNumber = 4',
              '',
              'print("Sum:", firstNumber + secondNumber)',
              'print("Difference:", firstNumber - secondNumber)',
              'print("Product:", firstNumber * secondNumber)',
              'print("Division:", firstNumber / secondNumber)',
              'print("Remainder:", firstNumber % secondNumber)',
            ].join('\n'),
            tests: [
              { name: 'Somme = 19', code: 'assert(printed("19"), "La somme (19) n\'apparaît pas")' },
              { name: 'Différence = 11', code: 'assert(printed("11"), "La différence (11) n\'apparaît pas")' },
              { name: 'Produit = 60', code: 'assert(printed("60"), "Le produit (60) n\'apparaît pas")' },
              { name: 'Division = 3.75', code: 'assert(printed("3.75"), "La division (3.75) n\'apparaît pas")' },
              { name: 'Reste = 3', code: 'assert(printed("3"), "Le reste (3) n\'apparaît pas")' },
            ],
          },

          {
            kind: 'exercise',
            id: 'm1c1-ex3',
            title: 'Exercice 3 — Manipulation de chaînes',
            difficulty: 'moyen',
            statement: [
              'À partir de `firstName = "John"` et `lastName = "Smith"` :',
              '',
              '1. construisez `fullName` par concaténation (avec un espace)',
              '2. affichez exactement : `Welcome John Smith to Lua programming!`',
            ].join('\n'),
            starter: [
              'local firstName = "John"',
              'local lastName = "Smith"',
              '',
              '-- Construisez fullName puis affichez le message de bienvenue',
            ].join('\n'),
            solution: [
              'local firstName = "John"',
              'local lastName = "Smith"',
              'local fullName = firstName .. " " .. lastName',
              'print("Welcome " .. fullName .. " to Lua programming!")',
            ].join('\n'),
            tests: [
              {
                name: 'Message de bienvenue exact',
                code: 'assert(printed("Welcome John Smith to Lua programming!"), "Le message attendu n\'apparaît pas")',
              },
            ],
            hints: ['On concatène avec l\'opérateur .. : a .. " " .. b'],
          },

          {
            kind: 'exercise',
            id: 'm1c1-ex4',
            title: 'Exercice 4 — Opérateurs logiques',
            difficulty: 'moyen',
            statement: [
              'Une personne peut conduire si elle est majeure **ET** a le permis **ET** possède un véhicule.',
              '',
              'Avec `isAdult = true`, `hasLicense = true`, `hasVehicle = false` :',
              '',
              '1. calculez `canDrive` à l\'aide des opérateurs logiques',
              '2. affichez `Can drive: false`',
            ].join('\n'),
            starter: [
              'local isAdult = true',
              'local hasLicense = true',
              'local hasVehicle = false',
              '',
              'local canDrive = ',
              'print("Can drive:", canDrive)',
            ].join('\n'),
            solution: [
              'local isAdult = true',
              'local hasLicense = true',
              'local hasVehicle = false',
              '',
              'local canDrive = isAdult and hasLicense and hasVehicle',
              'print("Can drive:", canDrive)',
            ].join('\n'),
            tests: [
              {
                name: 'Résultat : Can drive: false',
                code: 'assert(printed("Can drive:") and printed("false"), "On attend \'Can drive: false\'")',
              },
            ],
            hints: ['Combinez les trois booléens avec and : a and b and c'],
          },

          {
            kind: 'exercise',
            id: 'm1c1-ex5',
            title: 'Exercice 5 — Défis',
            difficulty: 'difficile',
            statement: [
              'Plusieurs petits défis avec des valeurs déjà fixées :',
              '',
              '1. **Aire** d\'un rectangle de longueur `8` et largeur `5` (résultat : `40`)',
              '2. **Périmètre** du même rectangle (résultat : `26`)',
              '3. Déterminez si `testNumber = 8` est pair grâce au modulo et affichez le mot `even` (sinon `odd`)',
              '',
              'Affichez chacun de ces résultats.',
            ].join('\n'),
            starter: [
              'local length = 8',
              'local width = 5',
              'local testNumber = 8',
              '',
              '-- 1. aire   2. périmètre   3. pair ou impair (even / odd)',
            ].join('\n'),
            solution: [
              'local length = 8',
              'local width = 5',
              'local testNumber = 8',
              '',
              'local area = length * width',
              'local perimeter = 2 * (length + width)',
              'print("Area:", area)',
              'print("Perimeter:", perimeter)',
              '',
              'local isEven = (testNumber % 2 == 0)',
              'print("The number " .. testNumber .. " is " .. (isEven and "even" or "odd"))',
            ].join('\n'),
            tests: [
              { name: 'Aire = 40', code: 'assert(printed("40"), "L\'aire (40) n\'apparaît pas")' },
              { name: 'Périmètre = 26', code: 'assert(printed("26"), "Le périmètre (26) n\'apparaît pas")' },
              { name: '8 est pair (even)', code: 'assert(printed("even"), "Le mot \'even\' n\'apparaît pas")' },
            ],
            hints: [
              'Aire = longueur × largeur, périmètre = 2 × (longueur + largeur).',
              'Un nombre est pair si n % 2 == 0.',
            ],
          },
        ],
      },

      {
        id: 'm1c2',
        title: 'Chapitre 2 — Structures de contrôle',
        summary: 'Conditions, boucles, break et return.',
        items: [
          { kind: 'lesson', id: 'm1c2-cours', title: 'Cours', content: chapitre2 },

          {
            kind: 'exercise',
            id: 'm1c2-ex1',
            title: 'Exercice 1 — Calculateur de notes',
            difficulty: 'facile',
            statement: [
              'À partir de `examScore = 87`, attribuez une lettre avec `if / elseif / else` :',
              '',
              '- `A` : 90–100 — `B` : 80–89 — `C` : 70–79 — `D` : 60–69 — `F` : 0–59',
              '',
              'Affichez la lettre. Avec 87, on attend la lettre `B`.',
            ].join('\n'),
            starter: ['local examScore = 87', '', '-- Déterminez la lettre puis affichez-la'].join('\n'),
            solution: [
              'local examScore = 87',
              'local grade',
              '',
              'if examScore >= 90 then',
              '    grade = "A"',
              'elseif examScore >= 80 then',
              '    grade = "B"',
              'elseif examScore >= 70 then',
              '    grade = "C"',
              'elseif examScore >= 60 then',
              '    grade = "D"',
              'else',
              '    grade = "F"',
              'end',
              '',
              'print("Grade:", grade)',
            ].join('\n'),
            tests: [{ name: '87 donne la lettre B', code: 'assert(printed("B"), "On attend la lettre B pour 87")' }],
          },

          {
            kind: 'exercise',
            id: 'm1c2-ex2',
            title: 'Exercice 2 — Table de multiplication',
            difficulty: 'facile',
            statement: [
              'Affichez la table de multiplication de `7`, de 1 à 10, avec une boucle `for`.',
              '',
              'Format attendu de chaque ligne : `7 x 1 = 7`, `7 x 2 = 14`, …, `7 x 10 = 70`.',
            ].join('\n'),
            starter: ['local number = 7', '', '-- Boucle for de 1 à 10'].join('\n'),
            solution: [
              'local number = 7',
              '',
              'for i = 1, 10 do',
              '    print(number .. " x " .. i .. " = " .. (number * i))',
              'end',
            ].join('\n'),
            tests: [
              { name: 'Ligne "7 x 1 = 7"', code: 'assert(printed("7 x 1 = 7"), "Ligne 7 x 1 = 7 manquante")' },
              { name: 'Ligne "7 x 5 = 35"', code: 'assert(printed("7 x 5 = 35"), "Ligne 7 x 5 = 35 manquante")' },
              { name: 'Ligne "7 x 10 = 70"', code: 'assert(printed("7 x 10 = 70"), "Ligne 7 x 10 = 70 manquante")' },
            ],
            hints: ['Utilisez for i = 1, 10 do ... end et concaténez avec ..'],
          },

          {
            kind: 'exercise',
            id: 'm1c2-ex3',
            title: 'Exercice 3 — Validateur de mot de passe',
            difficulty: 'difficile',
            statement: [
              'Définissez une **fonction globale** `IsPasswordValid(password)` qui renvoie `true` seulement si le mot de passe :',
              '',
              '1. fait au moins 8 caractères',
              '2. contient au moins une majuscule',
              '3. contient au moins une minuscule',
              '4. contient au moins un chiffre',
              '',
              'Indice : `string.find(password, "%u")` détecte une majuscule, `%l` une minuscule, `%d` un chiffre.',
            ].join('\n'),
            starter: [
              'function IsPasswordValid(password)',
              '    -- Renvoyez true ou false',
              'end',
              '',
              'print(IsPasswordValid("Password123"))',
            ].join('\n'),
            solution: [
              'function IsPasswordValid(password)',
              '    if #password < 8 then return false end',
              '    if not string.find(password, "%u") then return false end',
              '    if not string.find(password, "%l") then return false end',
              '    if not string.find(password, "%d") then return false end',
              '    return true',
              'end',
              '',
              'print(IsPasswordValid("Password123"))',
            ].join('\n'),
            tests: [
              { name: '"Password123" est valide', code: 'assert(IsPasswordValid("Password123") == true, "Devrait être valide")' },
              { name: '"abc" est trop court', code: 'assert(IsPasswordValid("abc") == false, "Trop court : devrait être invalide")' },
              { name: '"password123" sans majuscule', code: 'assert(IsPasswordValid("password123") == false, "Pas de majuscule : invalide")' },
              { name: '"Password" sans chiffre', code: 'assert(IsPasswordValid("Password") == false, "Pas de chiffre : invalide")' },
            ],
            hints: [
              '#password donne la longueur de la chaîne.',
              'string.find(s, "%d") renvoie nil si aucun chiffre n\'est présent.',
            ],
          },
        ],
      },

      {
        id: 'm1c3',
        title: 'Chapitre 3 — Tables, le cœur de Lua',
        summary: 'Tableaux, dictionnaires et introduction aux métatables.',
        items: [
          { kind: 'lesson', id: 'm1c3-cours', title: 'Cours', content: chapitre3 },

          {
            kind: 'exercise',
            id: 'm1c3-ex1',
            title: 'Exercice 1 — Tableaux',
            difficulty: 'facile',
            statement: [
              'À partir de `local fruits = {"apple", "banana"}` :',
              '',
              '1. ajoutez `"cherry"` à la fin avec `table.insert`',
              '2. affichez le **nombre** de fruits (avec `#`)',
              '3. affichez chaque fruit avec une boucle `ipairs`',
            ].join('\n'),
            starter: [
              'local fruits = {"apple", "banana"}',
              '',
              '-- 1. Ajoutez "cherry"   2. Affichez le nombre   3. Parcourez avec ipairs',
            ].join('\n'),
            solution: [
              'local fruits = {"apple", "banana"}',
              '',
              'table.insert(fruits, "cherry")',
              '',
              'print("Count:", #fruits)',
              '',
              'for index, fruit in ipairs(fruits) do',
              '    print(index, fruit)',
              'end',
            ].join('\n'),
            tests: [
              { name: 'Le tableau contient 3 fruits', code: 'assert(printed("3"), "On attend une longueur de 3")' },
              { name: '"apple" est affiché', code: 'assert(printed("apple"), "apple manquant")' },
              { name: '"cherry" a bien été ajouté', code: 'assert(printed("cherry"), "cherry manquant")' },
            ],
            hints: [
              'table.insert(t, valeur) ajoute la valeur à la fin du tableau.',
              '#fruits donne le nombre d\'éléments.',
            ],
          },

          {
            kind: 'exercise',
            id: 'm1c3-ex2',
            title: 'Exercice 2 — Dictionnaires',
            difficulty: 'moyen',
            statement: [
              'La table `player` est déjà créée (`name = "Alex"`, `level = 10`, `money = 500`).',
              '',
              '1. affichez le **nom** et le **niveau**',
              '2. ajoutez `250` à `money`',
              '3. affichez le nouveau total (`750`)',
            ].join('\n'),
            starter: [
              'local player = {',
              '    name = "Alex",',
              '    level = 10,',
              '    money = 500,',
              '}',
              '',
              '-- Affichez name et level, ajoutez 250 à money, puis affichez money',
            ].join('\n'),
            solution: [
              'local player = {',
              '    name = "Alex",',
              '    level = 10,',
              '    money = 500,',
              '}',
              '',
              'print("Name:", player.name)',
              'print("Level:", player.level)',
              '',
              'player.money = player.money + 250',
              'print("Money:", player.money)',
            ].join('\n'),
            tests: [
              { name: 'Le nom Alex est affiché', code: 'assert(printed("Alex"), "Le nom n\'apparaît pas")' },
              { name: 'Le niveau 10 est affiché', code: 'assert(printed("10"), "Le niveau n\'apparaît pas")' },
              { name: 'Le nouveau total est 750', code: 'assert(printed("750"), "On attend money = 750")' },
            ],
            hints: ['On accède à une clé avec player.name ou player["name"].'],
          },

          {
            kind: 'exercise',
            id: 'm1c3-ex3',
            title: 'Exercice 3 — Somme d\'un tableau',
            difficulty: 'moyen',
            statement: [
              'Écrivez une **fonction globale** `SumTable(numbers)` qui renvoie la somme de tous',
              'les nombres du tableau `numbers`. Un tableau vide doit renvoyer `0`.',
              '',
              'Indice : parcourez le tableau avec `ipairs` et accumulez le total.',
            ].join('\n'),
            starter: [
              'function SumTable(numbers)',
              '    -- Renvoyez la somme des éléments',
              'end',
              '',
              'print(SumTable({1, 2, 3, 4}))',
            ].join('\n'),
            solution: [
              'function SumTable(numbers)',
              '    local total = 0',
              '    for _, n in ipairs(numbers) do',
              '        total = total + n',
              '    end',
              '    return total',
              'end',
              '',
              'print(SumTable({1, 2, 3, 4}))',
            ].join('\n'),
            tests: [
              { name: 'SumTable({1,2,3,4}) == 10', code: 'assert(SumTable({1, 2, 3, 4}) == 10, "Somme attendue : 10")' },
              { name: 'SumTable({}) == 0', code: 'assert(SumTable({}) == 0, "Un tableau vide doit donner 0")' },
              { name: 'SumTable({10,-5}) == 5', code: 'assert(SumTable({10, -5}) == 5, "Somme attendue : 5")' },
            ],
            hints: ['Initialisez total à 0 avant la boucle, puis total = total + n.'],
          },

          {
            kind: 'exercise',
            id: 'm1c3-ex4',
            title: 'Exercice 4 — Inventaire',
            difficulty: 'difficile',
            statement: [
              'Un inventaire est une table dictionnaire de la forme `{ item = quantity }`.',
              '',
              'Écrivez deux **fonctions globales** :',
              '',
              '- `CountItems(inventory)` → le nombre **total** d\'objets (somme des quantités)',
              '- `HasItem(inventory, name)` → `true` si l\'objet existe et que sa quantité est > 0, sinon `false`',
              '',
              'Indice : parcourez un dictionnaire avec `pairs`.',
            ].join('\n'),
            starter: [
              'function CountItems(inventory)',
              '    -- Somme des quantités',
              'end',
              '',
              'function HasItem(inventory, name)',
              '    -- true / false',
              'end',
            ].join('\n'),
            solution: [
              'function CountItems(inventory)',
              '    local total = 0',
              '    for _, quantity in pairs(inventory) do',
              '        total = total + quantity',
              '    end',
              '    return total',
              'end',
              '',
              'function HasItem(inventory, name)',
              '    return inventory[name] ~= nil and inventory[name] > 0',
              'end',
            ].join('\n'),
            tests: [
              { name: 'CountItems({bread=2, water=5}) == 7', code: 'assert(CountItems({bread = 2, water = 5}) == 7, "Total attendu : 7")' },
              { name: 'CountItems({}) == 0', code: 'assert(CountItems({}) == 0, "Inventaire vide : 0")' },
              { name: 'HasItem trouve "bread"', code: 'assert(HasItem({bread = 2}, "bread") == true, "bread devrait être présent")' },
              { name: 'HasItem ne trouve pas "gold"', code: 'assert(HasItem({bread = 2}, "gold") == false, "gold ne devrait pas être présent")' },
            ],
            hints: [
              'pairs(t) parcourt toutes les paires clé/valeur d\'un dictionnaire.',
              'Pour HasItem, testez inventory[name] ~= nil.',
            ],
          },

          {
            kind: 'exercise',
            id: 'm1c3-ex5',
            title: 'Exercice 5 — Métatables et valeurs par défaut',
            difficulty: 'difficile',
            statement: [
              'Écrivez une **fonction globale** `WithDefaults(t, defaults)` qui renvoie la table `t`',
              'configurée de sorte que l\'accès à une **clé absente** de `t` renvoie la valeur',
              'correspondante dans `defaults`.',
              '',
              'Indice : utilisez `setmetatable(t, { __index = defaults })`.',
            ].join('\n'),
            starter: [
              'function WithDefaults(t, defaults)',
              '    -- Associez une métatable avec __index',
              'end',
            ].join('\n'),
            solution: [
              'function WithDefaults(t, defaults)',
              '    return setmetatable(t, { __index = defaults })',
              'end',
            ].join('\n'),
            tests: [
              {
                name: 'La valeur propre est conservée (hp = 80)',
                code: 'assert(WithDefaults({hp = 80}, {hp = 100, armor = 50}).hp == 80, "hp propre doit valoir 80")',
              },
              {
                name: 'La valeur par défaut est utilisée (armor = 50)',
                code: 'assert(WithDefaults({hp = 80}, {hp = 100, armor = 50}).armor == 50, "armor doit venir des defaults")',
              },
              {
                name: 'Clé totalement absente -> défaut',
                code: 'local s = WithDefaults({}, {speed = 5}); assert(s.speed == 5, "speed doit valoir 5")',
              },
            ],
            hints: [
              '__index peut être une table : les clés manquantes y sont cherchées.',
              'setmetatable renvoie la table passée en premier argument.',
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'm2',
    title: 'Module 2 — Programmation avancée',
    summary: 'Fonctions, chaînes de caractères et modules.',
    chapters: [
      {
        id: 'm2c4',
        title: 'Chapitre 4 — Fonctions',
        summary: 'Paramètres, retours multiples, closures, fonctions variadiques.',
        items: [
          { kind: 'lesson', id: 'm2c4-cours', title: 'Cours', content: chapitre4 },

          {
            kind: 'exercise',
            id: 'm2c4-ex1',
            title: 'Exercice 1 — Définir une fonction',
            difficulty: 'facile',
            statement: [
              'Écrivez une **fonction globale** `Greet(name)` qui **renvoie** (avec `return`)',
              'la chaîne `Hello <name>!`.',
              '',
              'Exemple : `Greet("Alex")` doit renvoyer `Hello Alex!`.',
            ].join('\n'),
            starter: [
              'function Greet(name)',
              '    -- Renvoyez la chaîne de bienvenue',
              'end',
              '',
              'print(Greet("Alex"))',
            ].join('\n'),
            solution: [
              'function Greet(name)',
              '    return "Hello " .. name .. "!"',
              'end',
              '',
              'print(Greet("Alex"))',
            ].join('\n'),
            tests: [
              { name: 'Greet("Alex") == "Hello Alex!"', code: 'assert(Greet("Alex") == "Hello Alex!", "Résultat attendu : Hello Alex!")' },
              { name: 'Greet("Sam") == "Hello Sam!"', code: 'assert(Greet("Sam") == "Hello Sam!", "Résultat attendu : Hello Sam!")' },
            ],
            hints: ['Utilisez return et la concaténation : "Hello " .. name .. "!"'],
          },

          {
            kind: 'exercise',
            id: 'm2c4-ex2',
            title: 'Exercice 2 — Retours multiples',
            difficulty: 'moyen',
            statement: [
              'Écrivez une **fonction globale** `MinMax(a, b)` qui renvoie **deux valeurs** :',
              "d'abord le plus petit des deux nombres, puis le plus grand.",
              '',
              'Exemple : `local lo, hi = MinMax(8, 3)` doit donner `lo = 3` et `hi = 8`.',
            ].join('\n'),
            starter: [
              'function MinMax(a, b)',
              '    -- Renvoyez le minimum puis le maximum',
              'end',
              '',
              'print(MinMax(8, 3))',
            ].join('\n'),
            solution: [
              'function MinMax(a, b)',
              '    if a <= b then',
              '        return a, b',
              '    else',
              '        return b, a',
              '    end',
              'end',
              '',
              'print(MinMax(8, 3))',
            ].join('\n'),
            tests: [
              { name: 'MinMax(3, 8) -> 3, 8', code: 'local lo, hi = MinMax(3, 8); assert(lo == 3 and hi == 8, "Attendu : 3, 8")' },
              { name: 'MinMax(10, 2) -> 2, 10', code: 'local lo, hi = MinMax(10, 2); assert(lo == 2 and hi == 10, "Attendu : 2, 10")' },
              { name: 'MinMax(5, 5) -> 5, 5', code: 'local lo, hi = MinMax(5, 5); assert(lo == 5 and hi == 5, "Attendu : 5, 5")' },
            ],
            hints: ['On renvoie plusieurs valeurs en les séparant par une virgule : return a, b'],
          },

          {
            kind: 'exercise',
            id: 'm2c4-ex3',
            title: 'Exercice 3 — Arguments par défaut',
            difficulty: 'moyen',
            statement: [
              'Écrivez une **fonction globale** `CreatePlayer(name, health)` qui renvoie une table',
              '`{ name = ..., health = ... }`.',
              '',
              "Si `health` n'est pas fourni (`nil`), utilisez **100** par défaut.",
            ].join('\n'),
            starter: [
              'function CreatePlayer(name, health)',
              '    -- Renvoyez une table avec name et health (défaut 100)',
              'end',
            ].join('\n'),
            solution: [
              'function CreatePlayer(name, health)',
              '    health = health or 100',
              '    return { name = name, health = health }',
              'end',
            ].join('\n'),
            tests: [
              { name: 'Sans health -> 100', code: 'local p = CreatePlayer("Alex"); assert(p.name == "Alex" and p.health == 100, "health par défaut doit valoir 100")' },
              { name: 'Avec health = 50', code: 'local p = CreatePlayer("Sam", 50); assert(p.health == 50, "health fourni doit valoir 50")' },
            ],
            hints: ['Idiome : health = health or 100'],
          },

          {
            kind: 'exercise',
            id: 'm2c4-ex4',
            title: 'Exercice 4 — Fonction variadique',
            difficulty: 'moyen',
            statement: [
              'Écrivez une **fonction globale** `Sum(...)` qui renvoie la somme de **tous** ses',
              'arguments, quel que soit leur nombre. `Sum()` (sans argument) doit renvoyer `0`.',
              '',
              "Indice : `select('#', ...)` donne le nombre d'arguments ; `select(i, ...)` renvoie",
              "l'argument en position `i`.",
            ].join('\n'),
            starter: [
              'function Sum(...)',
              '    -- Additionnez tous les arguments',
              'end',
              '',
              'print(Sum(1, 2, 3, 4))',
            ].join('\n'),
            solution: [
              'function Sum(...)',
              '    local total = 0',
              "    for i = 1, select('#', ...) do",
              '        total = total + select(i, ...)',
              '    end',
              '    return total',
              'end',
              '',
              'print(Sum(1, 2, 3, 4))',
            ].join('\n'),
            tests: [
              { name: 'Sum(1, 2, 3) == 6', code: 'assert(Sum(1, 2, 3) == 6, "Attendu : 6")' },
              { name: 'Sum() == 0', code: 'assert(Sum() == 0, "Sans argument : 0")' },
              { name: 'Sum(10, -2, 5) == 13', code: 'assert(Sum(10, -2, 5) == 13, "Attendu : 13")' },
              { name: 'Sum(7) == 7', code: 'assert(Sum(7) == 7, "Attendu : 7")' },
            ],
            hints: ["Bouclez de 1 à select('#', ...) et ajoutez select(i, ...) au total."],
          },

          {
            kind: 'exercise',
            id: 'm2c4-ex5',
            title: 'Exercice 5 — Closures',
            difficulty: 'difficile',
            statement: [
              'Écrivez une **fonction globale** `MakeCounter()` qui renvoie une **fonction**.',
              "Chaque appel de la fonction renvoyée donne l'entier suivant, en commençant à `1`",
              '(1, puis 2, puis 3…).',
              '',
              'Deux compteurs créés séparément doivent être **indépendants**.',
            ].join('\n'),
            starter: [
              'function MakeCounter()',
              '    -- Renvoyez une fonction qui compte 1, 2, 3, ...',
              'end',
              '',
              'local count = MakeCounter()',
              'print(count())',
              'print(count())',
            ].join('\n'),
            solution: [
              'function MakeCounter()',
              '    local count = 0',
              '    return function()',
              '        count = count + 1',
              '        return count',
              '    end',
              'end',
              '',
              'local count = MakeCounter()',
              'print(count())',
              'print(count())',
            ].join('\n'),
            tests: [
              { name: 'Compte 1, 2, 3', code: 'local c = MakeCounter(); assert(c() == 1 and c() == 2 and c() == 3, "Le compteur doit donner 1, 2, 3")' },
              { name: 'Compteurs indépendants', code: 'local a = MakeCounter(); local b = MakeCounter(); a(); a(); assert(b() == 1, "Chaque compteur a son propre état")' },
            ],
            hints: [
              'Déclarez une variable locale count AVANT de renvoyer la fonction.',
              'La fonction renvoyée capture (closure) cette variable count.',
            ],
          },

          {
            kind: 'exercise',
            id: 'm2c4-ex6',
            title: 'Exercice 6 — Fonction d\'ordre supérieur',
            difficulty: 'difficile',
            statement: [
              'Écrivez une **fonction globale** `ApplyToAll(numbers, fn)` qui renvoie un **nouveau**',
              'tableau contenant `fn` appliquée à chaque élément de `numbers`.',
              '',
              'Exemple : `ApplyToAll({1, 2, 3}, function(x) return x * 2 end)` renvoie `{2, 4, 6}`.',
            ].join('\n'),
            starter: [
              'function ApplyToAll(numbers, fn)',
              '    -- Renvoyez un nouveau tableau avec fn appliquée à chaque élément',
              'end',
            ].join('\n'),
            solution: [
              'function ApplyToAll(numbers, fn)',
              '    local result = {}',
              '    for i, n in ipairs(numbers) do',
              '        result[i] = fn(n)',
              '    end',
              '    return result',
              'end',
            ].join('\n'),
            tests: [
              { name: 'Double chaque élément', code: 'local r = ApplyToAll({1, 2, 3}, function(x) return x * 2 end); assert(r[1] == 2 and r[2] == 4 and r[3] == 6, "Attendu : {2, 4, 6}")' },
              { name: 'Met au carré', code: 'local r = ApplyToAll({2, 3, 4}, function(x) return x * x end); assert(r[1] == 4 and r[2] == 9 and r[3] == 16, "Attendu : {4, 9, 16}")' },
              { name: 'Tableau vide', code: 'local r = ApplyToAll({}, function(x) return x end); assert(#r == 0, "Un tableau vide doit donner un tableau vide")' },
            ],
            hints: [
              'Créez un tableau result vide, parcourez numbers avec ipairs.',
              'Appelez fn(n) et stockez le résultat dans result[i].',
            ],
          },
        ],
      },
      { id: 'm2c5', title: 'Chapitre 5 — Gestion des chaînes', summary: 'Patterns, formatage, bibliothèque string.', comingSoon: true, items: [] },
      { id: 'm2c6', title: 'Chapitre 6 — Modules et packages', summary: 'require(), organisation du code.', comingSoon: true, items: [] },
    ],
  },

  {
    id: 'm3',
    title: 'Module 3 — Concepts avancés',
    summary: 'Métaprogrammation, coroutines et gestion d\'erreurs.',
    chapters: [
      { id: 'm3c7', title: 'Chapitre 7 — Métatables et POO', summary: '__index, __newindex, surcharge d\'opérateurs.', comingSoon: true, items: [] },
      { id: 'm3c8', title: 'Chapitre 8 — Coroutines', summary: 'create, resume, yield.', comingSoon: true, items: [] },
      { id: 'm3c9', title: 'Chapitre 9 — Gestion d\'erreurs', summary: 'pcall, xpcall, débogage.', comingSoon: true, items: [] },
    ],
  },

  {
    id: 'm4',
    title: 'Module 4 — Préparation à FiveM',
    summary: 'Architecture client-serveur, natives et projet pratique.',
    chapters: [
      { id: 'm4c10', title: 'Chapitre 10 — Lua dans FiveM', summary: 'Architecture, événements, ressources.', comingSoon: true, items: [] },
      { id: 'm4c11', title: 'Chapitre 11 — Natives et API FiveM', summary: 'Natives GTA V, CitizenFX, NUI.', comingSoon: true, items: [] },
      { id: 'm4c12', title: 'Chapitre 12 — Projet pratique', summary: 'Création d\'une ressource complète.', comingSoon: true, items: [] },
    ],
  },
]
